const KEY = 'ledger-v1';
const defaults = { habits:[['Wash face','daily'],['Drink water','daily'],['Shower','daily'],['Make bed','daily'],['Maintain finger nails','weekly'],['Trim eyebrows','weekly']].map((x,i)=>({id:'seed-'+i,name:x[0],frequency:x[1],createdAt:new Date().toISOString()})), completions:{}, transactions:[] };
let data; try { data=JSON.parse(localStorage.getItem(KEY)) || defaults } catch { data=defaults }
let transactionType='income';
const $=s=>document.querySelector(s); const dateKey=(value=new Date())=>{const d=typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)?new Date(value+'T12:00:00'):new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}; const today=dateKey();
const prettyDate=(d=new Date())=>d.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
const completed=(id,key=today)=>!!data.completions[key]?.includes(id);
function periodKey(h,date=today){ if(h.frequency==='daily')return date; const d=new Date(date+'T12:00:00'); d.setDate(d.getDate()-d.getDay());return dateKey(d) }
function toggleHabit(id){const h=data.habits.find(x=>x.id===id), k=periodKey(h);let entries=data.completions[k]||[];data.completions[k]=entries.includes(id)?entries.filter(x=>x!==id):[...entries,id];save();render()}
function habitEl(h){const done=completed(h.id,periodKey(h));return `<article class="habit ${done?'done':''}"><button class="habit-main" data-habit="${h.id}" aria-label="Mark ${escapeHtml(h.name)} as ${done?'incomplete':'complete'}"><span class="habit-check">${done?'✓':''}</span><span class="habit-name">${escapeHtml(h.name)}</span><span class="habit-meta">${h.frequency==='weekly'?'WEEKLY':'DAILY'}</span></button><button class="habit-delete" data-delete-habit="${h.id}" aria-label="Delete ${escapeHtml(h.name)}">×</button></article>`}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function streak(){let count=0,d=new Date();while(true){const k=dateKey(d), ds=data.habits.filter(h=>h.frequency==='daily'&&h.createdAt.slice(0,10)<=k);if(!ds.length||!ds.every(h=>completed(h.id,k)))break;count++;d.setDate(d.getDate()-1)}return count}
function getStats(){const all=data.habits;let possible=0,done=0;Object.entries(data.completions).forEach(([key,ids])=>{const count=all.filter(h=>h.frequency==='daily'?h.createdAt.slice(0,10)<=key:periodKey(h,key)===key).length;possible+=count;done+=ids.length});const total=data.transactions.reduce((s,x)=>s+(x.type==='income'?x.amount:-x.amount),0);return{all,possible,done,balance:total,streak:streak()}}
function fmt(n){return new Intl.NumberFormat(undefined,{style:'currency',currency:'USD'}).format(n)}
function render(){const daily=data.habits.filter(h=>h.frequency==='daily'),weekly=data.habits.filter(h=>h.frequency==='weekly');const dailyDone=daily.filter(h=>completed(h.id)).length,weeklyDone=weekly.filter(h=>completed(h.id,periodKey(h))).length,total=daily.length+weekly.length, done=dailyDone+weeklyDone,pct=total?Math.round(done/total*100):0,stats=getStats();
 $('#dateLabel').textContent=prettyDate().toUpperCase();$('#greeting').textContent=new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening';$('#streakValue').textContent=stats.streak;$('#todayPercent').textContent=pct+'%';$('#todayProgress').style.width=pct+'%';$('#progressCaption').textContent=total?(pct===100?'Everything is checked off. Beautiful.':`${total-done} habit${total-done===1?'':'s'} left to keep your promise.`):'Add your first habit to begin.';$('#dailyCount').textContent=`${dailyDone} of ${daily.length}`;$('#weeklyCount').textContent=`${weeklyDone} of ${weekly.length}`;$('#dailyHabits').innerHTML=daily.map(habitEl).join('')||'<div class="empty">No daily habits yet.</div>';$('#weeklyHabits').innerHTML=weekly.map(habitEl).join('')||'<div class="empty">No weekly habits yet.</div>';
 const income=data.transactions.filter(x=>x.type==='income').reduce((s,x)=>s+x.amount,0),out=data.transactions.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amount,0);$('#balanceValue').textContent=fmt(stats.balance);$('#incomeTotal').textContent='+'+fmt(income)+' in';$('#expenseTotal').textContent='−'+fmt(out)+' out';$('#transactionList').innerHTML=data.transactions.slice().reverse().map(t=>`<div class="transaction"><span class="transaction-icon">${t.type==='income'?'↙':'↗'}</span><span class="transaction-info">${escapeHtml(t.note)}<small>${prettyDate(t.date)}</small></span><span class="transaction-amount ${t.type}">${t.type==='income'?'+':'−'}${fmt(t.amount)}</span></div>`).join('')||'<div class="empty">No entries yet. Your cash story starts here.</div>';
 const history=Object.entries(data.completions).filter(([,ids])=>ids.length).sort((a,b)=>b[0].localeCompare(a[0]));$('#historyTotal').textContent=history.reduce((s,[,a])=>s+a.length,0);$('#historyList').innerHTML=history.map(([k,ids])=>`<article class="history-day"><header><strong>${prettyDate(k+'T12:00:00')}</strong><span>${ids.length} complete</span></header><div class="history-habits">${ids.map(id=>{const h=data.habits.find(x=>x.id===id);return h?`<span>✓ ${escapeHtml(h.name)}</span>`:''}).join('')}</div></article>`).join('')||'<div class="empty">Complete a habit and it will be kept here.</div>';
 $('#statsStreak').textContent=stats.streak+' day'+(stats.streak===1?'':'s');$('#streakSubtext').textContent=stats.streak?'Keep your rhythm going.':'Complete every daily habit to begin.';$('#statsCompletion').textContent=stats.possible?Math.round(stats.done/stats.possible*100)+'%':'0%';$('#statsHabits').textContent=stats.all.length;$('#statsEntries').textContent=history.reduce((s,[,a])=>s+a.length,0);$('#statsCash').textContent=fmt(stats.balance);
}
document.addEventListener('click',e=>{const close=e.target.closest('[data-close-dialog]');if(close){close.closest('dialog').close();return}const remove=e.target.closest('[data-delete-habit]');if(remove){const id=remove.dataset.deleteHabit,h=data.habits.find(x=>x.id===id);if(h&&confirm(`Delete “${h.name}”? This will also remove its completion history.`)){data.habits=data.habits.filter(x=>x.id!==id);Object.keys(data.completions).forEach(key=>{data.completions[key]=data.completions[key].filter(x=>x!==id);if(!data.completions[key].length)delete data.completions[key]});save();render()}return}const habit=e.target.closest('[data-habit]');if(habit)toggleHabit(habit.dataset.habit);const nav=e.target.closest('.nav-item');if(nav){document.querySelectorAll('.nav-item,.view').forEach(x=>x.classList.remove('active'));nav.classList.add('active');$('#'+nav.dataset.view).classList.add('active')}});
$('#addHabitButton').onclick=()=>$('#habitDialog').showModal();$('#habitForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return; const name=$('#habitName').value.trim();if(!name){e.preventDefault();return}data.habits.push({id:crypto.randomUUID(),name,frequency:$('#habitFrequency').value,createdAt:new Date().toISOString()});save();e.target.reset();render()});
function openTransaction(type){transactionType=type;$('#transactionDialogLabel').textContent=type==='income'?'CASH IN':'CASH OUT';$('#transactionDialogTitle').textContent=type==='income'?'Add money':'Remove money';$('#transactionSubmit').textContent=type==='income'?'Add to balance':'Remove from balance';$('#transactionDialog').showModal()}$('#addIncomeButton').onclick=()=>openTransaction('income');$('#addExpenseButton').onclick=()=>openTransaction('expense');$('#transactionForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const amount=Number($('#transactionAmount').value),note=$('#transactionNote').value.trim();if(!amount||!note){e.preventDefault();return}data.transactions.push({id:crypto.randomUUID(),type:transactionType,amount,note,date:new Date().toISOString()});save();e.target.reset();render()});
$('#clearTransactions').onclick=()=>{if(data.transactions.length&&confirm('Clear all cash transactions? This cannot be undone.')){data.transactions=[];save();render()}};$('#exportButton').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`ledger-backup-${today}.json`;a.click();URL.revokeObjectURL(url)};render();
