const KEY = 'ledger-v1';
const timedPrograms={hard75:{label:'75 HARD',days:75,mark:'75',rules:['Follow your diet — no cheat meals','No alcohol','Workout 1 — 45 minutes','Workout 2 — 45 minutes outdoors','Drink one gallon of water','Read 10 pages of nonfiction','Take a progress photo']},reset14:{label:'14-DAY RESET',days:14,mark:'14',rules:['Make your bed','Tidy for 10 minutes','Take a 20-minute walk','No screens 30 minutes before bed']},move30:{label:'30-DAY MOVEMENT',days:30,mark:'30',rules:['Move your body for 30 minutes','Stretch for 10 minutes','Drink 8 glasses of water']},read30:{label:'30-DAY READING',days:30,mark:'30',rules:['Read for 20 minutes','Write down one takeaway']}};
const defaults = { habits:[], completions:{}, transactions:[], profile:{name:'',theme:'forest',onboarded:false,hard75:{enabled:false,startDate:''},connectedApps:{bevel:false,calendar:false,notion:false,todoist:false,forest:false}}, plus:{moods:{},notes:{},goals:[]} };
let data; try { data=JSON.parse(localStorage.getItem(KEY)) || defaults } catch { data=defaults }
if(!data.profile)data.profile={name:'',theme:'forest',onboarded:false,hard75:{enabled:false,startDate:''},connectedApps:{bevel:false,calendar:false,notion:false,todoist:false,forest:false}};if(!data.profile.theme)data.profile.theme='forest';if(data.profile.onboarded===undefined)data.profile.onboarded=!!data.profile.name;if(!data.profile.programs)data.profile.programs={};Object.keys(timedPrograms).forEach(key=>{if(!data.profile.programs[key])data.profile.programs[key]=key==='hard75'&&data.profile.hard75?data.profile.hard75:{enabled:false,startDate:''}});if(!data.profile.connectedApps)data.profile.connectedApps={bevel:false,calendar:false,notion:false,todoist:false,forest:false}; let transactionType='income',timerHabitId=null,timerRemaining=0,timerRunning=false,timerInterval=null;
if(!data.plus)data.plus={moods:{},notes:{},goals:[]};if(!data.plus.moods)data.plus.moods={};if(!data.plus.notes)data.plus.notes={};if(!data.plus.goals)data.plus.goals=[];
const $=s=>document.querySelector(s); const dateKey=(value=new Date())=>{const d=typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)?new Date(value+'T12:00:00'):new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}; const today=dateKey();
const prettyDate=(d=new Date())=>(typeof d==='string'?new Date(d):d).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
const completed=(id,key=today)=>!!data.completions[key]?.includes(id);
function periodKey(h,date=today){ if(h.frequency==='daily')return date; const d=new Date(date+'T12:00:00'); d.setDate(d.getDate()-d.getDay());return dateKey(d) }
function toggleHabit(id){const h=data.habits.find(x=>x.id===id), k=periodKey(h);let entries=data.completions[k]||[];data.completions[k]=entries.includes(id)?entries.filter(x=>x!==id):[...entries,id];save();render()}
function habitEl(h){const done=completed(h.id,periodKey(h));return `<article class="habit ${done?'done':''}"><button class="habit-main" data-habit="${h.id}" aria-label="Mark ${escapeHtml(h.name)} as ${done?'incomplete':'complete'}"><span class="habit-check">${done?'✓':''}</span><span class="habit-name">${escapeHtml(h.name)}</span><span class="habit-meta">${h.category||(h.frequency==='weekly'?'WEEKLY':'DAILY')}</span></button>${h.durationMinutes?`<button class="habit-timer" data-timer-habit="${h.id}" aria-label="Start ${h.durationMinutes} minute timer for ${escapeHtml(h.name)}">⏱ ${h.durationMinutes}m</button>`:''}<button class="habit-delete" data-delete-habit="${h.id}" aria-label="Delete ${escapeHtml(h.name)}">×</button></article>`}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function streak(){let count=0,d=new Date();while(true){const k=dateKey(d), ds=data.habits.filter(h=>h.frequency==='daily'&&h.createdAt.slice(0,10)<=k);if(!ds.length||!ds.every(h=>completed(h.id,k)))break;count++;d.setDate(d.getDate()-1)}return count}
function getStats(){const all=data.habits;let possible=0,done=0;Object.entries(data.completions).forEach(([key,ids])=>{const count=all.filter(h=>h.frequency==='daily'?h.createdAt.slice(0,10)<=key:periodKey(h,key)===key).length;possible+=count;done+=ids.length});const total=data.transactions.reduce((s,x)=>s+(x.type==='income'?x.amount:-x.amount),0);return{all,possible,done,balance:total,streak:streak()}}
function fmt(n){return new Intl.NumberFormat(undefined,{style:'currency',currency:'USD'}).format(n)}
function renderCashChart(){const days=[];for(let offset=6;offset>=0;offset--){const d=new Date();d.setDate(d.getDate()-offset);days.push(dateKey(d))}const values=days.map(day=>data.transactions.filter(transaction=>dateKey(transaction.date)===day).reduce((total,transaction)=>total+(transaction.type==='income'?transaction.amount:-transaction.amount),0));const maximum=Math.max(1,...values.map(value=>Math.abs(value)));const net=values.reduce((total,value)=>total+value,0);$('#chartSummary').textContent=net?`${net>0?'+':''}${fmt(net)} this week`:'No activity yet';$('#cashChart').innerHTML=days.map((day,index)=>{const value=values[index],height=value?Math.max(8,Math.round(Math.abs(value)/maximum*78)):3,label=new Date(day+'T12:00:00').toLocaleDateString(undefined,{weekday:'narrow'});return `<div class="chart-day" title="${prettyDate(day+'T12:00:00')}: ${value>=0?'+':''}${fmt(value)}"><i class="chart-bar ${value<0?'expense':''}" style="height:${height}px"></i><small>${label}</small></div>`}).join('')}
function renderPlus(){const days=[];for(let offset=27;offset>=0;offset--){const d=new Date();d.setDate(d.getDate()-offset);days.push(dateKey(d))}$('#heatMap').innerHTML=days.map(day=>{const count=data.completions[day]?.length||0,level=count?Math.min(3,Math.ceil(count/2)):0;return `<i class="heat-day level-${level}" title="${day}: ${count} habits"></i>`}).join('');const week=days.slice(-7),complete=week.reduce((sum,day)=>sum+(data.completions[day]?.length||0),0),possible=Math.max(1,data.habits.filter(h=>h.frequency==='daily').length*7);$('#reviewCompletion').textContent=`${Math.round(complete/possible*100)}% complete`;const moodValues=week.map(day=>data.plus.moods[day]).filter(Boolean);$('#reviewText').textContent=moodValues.length?`Average energy: ${(moodValues.reduce((a,b)=>a+b,0)/moodValues.length).toFixed(1)} / 10`:'Check in each day to see your weekly energy trend.';$('#dailyNote').value=data.plus.notes[today]||'';const apps={bevel:{name:'Bevel',sub:'Health and recovery',mark:'B',url:'https://www.bevel.health/'},calendar:{name:'Google Calendar',sub:'Plan your schedule',mark:'31',url:'https://calendar.google.com/'},notion:{name:'Notion',sub:'Notes and projects',mark:'N',url:'https://www.notion.so/'},todoist:{name:'Todoist',sub:'Tasks and priorities',mark:'✓',url:'https://todoist.com/'},forest:{name:'Forest',sub:'Stay focused',mark:'♣',url:'https://www.forestapp.cc/'}};const selected=Object.entries(apps).filter(([key])=>data.profile.connectedApps[key]);$('#connectedAppLinks').innerHTML=selected.map(([,app])=>`<a href="${app.url}" target="_blank" rel="noopener"><span>${app.mark}</span><div><strong>${app.name}</strong><small>${app.sub}</small></div><b>↗</b></a>`).join('')||'<div class="empty">Choose apps in Customize to add quick links here.</div>';document.querySelectorAll('[data-mood]').forEach(button=>button.classList.toggle('active',Number(button.dataset.mood)===data.plus.moods[today]))}
function updateTimerDisplay(){const minutes=Math.floor(timerRemaining/60),seconds=timerRemaining%60;$('#timerDisplay').textContent=`${minutes}:${String(seconds).padStart(2,'0')}`;$('#timerToggle').textContent=timerRunning?'Pause timer':timerRemaining?'Start timer':'Complete'}
function stopTimer(){clearInterval(timerInterval);timerInterval=null;timerRunning=false}
function completeTimer(){stopTimer();const habit=data.habits.find(h=>h.id===timerHabitId);if(habit&&!completed(habit.id,periodKey(habit)))toggleHabit(habit.id);$('#timerMessage').textContent='Focus complete. Nice work.';timerRemaining=0;updateTimerDisplay()}
function openTimer(id){const habit=data.habits.find(h=>h.id===id);if(!habit)return;stopTimer();timerHabitId=id;timerRemaining=habit.durationMinutes*60;$('#timerHabitName').textContent=habit.name;$('#timerMessage').textContent='Ready when you are.';updateTimerDisplay();$('#timerDialog').showModal()}
function toggleTimer(){if(!timerRemaining){completeTimer();return}timerRunning=!timerRunning;if(timerRunning)timerInterval=setInterval(()=>{timerRemaining--;if(timerRemaining<=0)completeTimer();else updateTimerDisplay()},1000);else clearInterval(timerInterval);updateTimerDisplay()}
function programStatus(key){const program=data.profile.programs[key],definition=timedPrograms[key];if(!program?.enabled)return null;const start=program.startDate||today;const elapsed=Math.max(0,Math.floor((new Date(today+'T12:00:00')-new Date(start+'T12:00:00'))/86400000)+1);return {definition,day:Math.min(definition.days,elapsed),remaining:Math.max(0,definition.days-elapsed)}}
function render(){document.body.className=data.profile.theme==='forest'?'':`theme-${data.profile.theme}`;const daily=data.habits.filter(h=>h.frequency==='daily'),weekly=data.habits.filter(h=>h.frequency==='weekly');const dailyDone=daily.filter(h=>completed(h.id)).length,weeklyDone=weekly.filter(h=>completed(h.id,periodKey(h))).length,total=daily.length+weekly.length, done=dailyDone+weeklyDone,pct=total?Math.round(done/total*100):0,stats=getStats();
 $('#dateLabel').textContent=prettyDate().toUpperCase();const timeGreeting=new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening';$('#greeting').textContent=`${timeGreeting}${data.profile.name?', '+data.profile.name:''}`;const activePrograms=Object.keys(timedPrograms).map(programStatus).filter(Boolean);$('#programCards').innerHTML=activePrograms.map(status=>`<section class="hard-card"><span>${status.definition.mark}</span><div><p>${status.definition.label}</p><strong>${status.remaining?`Day ${status.day} of ${status.definition.days}`:`${status.definition.label} complete`}</strong><small>${status.remaining?`${status.remaining} day${status.remaining===1?'':'s'} remaining`:'You made it.'}</small></div></section>`).join('');$('#streakValue').textContent=stats.streak;$('#todayPercent').textContent=pct+'%';$('#todayProgress').style.width=pct+'%';$('#progressCaption').textContent=total?(pct===100?'Everything is checked off. Beautiful.':`${total-done} habit${total-done===1?'':'s'} left to keep your promise.`):'Add your first habit to begin.';$('#dailyCount').textContent=`${dailyDone} of ${daily.length}`;$('#weeklyCount').textContent=`${weeklyDone} of ${weekly.length}`;$('#dailyHabits').innerHTML=daily.map(habitEl).join('')||'<div class="empty">No daily habits yet.</div>';$('#weeklyHabits').innerHTML=weekly.map(habitEl).join('')||'<div class="empty">No weekly habits yet.</div>';
 const income=data.transactions.filter(x=>x.type==='income').reduce((s,x)=>s+x.amount,0),out=data.transactions.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amount,0);$('#balanceValue').textContent=fmt(stats.balance);$('#incomeTotal').textContent='+'+fmt(income)+' in';$('#expenseTotal').textContent='−'+fmt(out)+' out';$('#transactionList').innerHTML=data.transactions.slice().reverse().map(t=>`<div class="transaction"><span class="transaction-icon">${t.type==='income'?'↙':'↗'}</span><span class="transaction-info">${escapeHtml(t.note)}<small>${prettyDate(t.date)}</small></span><span class="transaction-amount ${t.type}">${t.type==='income'?'+':'−'}${fmt(t.amount)}</span></div>`).join('')||'<div class="empty">No entries yet. Your cash story starts here.</div>';renderCashChart();
 const history=Object.entries(data.completions).filter(([,ids])=>ids.length).sort((a,b)=>b[0].localeCompare(a[0]));$('#historyTotal').textContent=history.reduce((s,[,a])=>s+a.length,0);$('#historyList').innerHTML=history.map(([k,ids])=>`<article class="history-day"><header><strong>${prettyDate(k+'T12:00:00')}</strong><span>${ids.length} complete</span></header><div class="history-habits">${ids.map(id=>{const h=data.habits.find(x=>x.id===id);return h?`<span>✓ ${escapeHtml(h.name)}</span>`:''}).join('')}</div></article>`).join('')||'<div class="empty">Complete a habit and it will be kept here.</div>';
 $('#statsStreak').textContent=stats.streak+' day'+(stats.streak===1?'':'s');$('#streakSubtext').textContent=stats.streak?'Keep your rhythm going.':'Complete every daily habit to begin.';$('#statsCompletion').textContent=stats.possible?Math.round(stats.done/stats.possible*100)+'%':'0%';$('#statsHabits').textContent=stats.all.length;$('#statsEntries').textContent=history.reduce((s,[,a])=>s+a.length,0);$('#statsCash').textContent=fmt(stats.balance);renderPlus();
}
document.addEventListener('click',e=>{const close=e.target.closest('[data-close-dialog]');if(close){if(close.closest('dialog')?.id==='timerDialog')stopTimer();close.closest('dialog').close();return}const timer=e.target.closest('[data-timer-habit]');if(timer){openTimer(timer.dataset.timerHabit);return}const goal=e.target.closest('[data-delete-goal]');if(goal){data.plus.goals=data.plus.goals.filter(item=>item.id!==goal.dataset.deleteGoal);save();render();return}const remove=e.target.closest('[data-delete-habit]');if(remove){const id=remove.dataset.deleteHabit,h=data.habits.find(x=>x.id===id);if(h&&confirm(`Delete “${h.name}”? This will also remove its completion history.`)){data.habits=data.habits.filter(x=>x.id!==id);Object.keys(data.completions).forEach(key=>{data.completions[key]=data.completions[key].filter(x=>x!==id);if(!data.completions[key].length)delete data.completions[key]});save();render()}return}const habit=e.target.closest('[data-habit]');if(habit)toggleHabit(habit.dataset.habit);const nav=e.target.closest('.nav-item');if(nav){document.querySelectorAll('.nav-item,.view').forEach(x=>x.classList.remove('active'));nav.classList.add('active');$('#'+nav.dataset.view).classList.add('active')}});
$('#addHabitButton').onclick=()=>$('#habitDialog').showModal();$('#habitForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return; const name=$('#habitName').value.trim(),durationMinutes=Number($('#habitMinutes').value)||0;if(!name){e.preventDefault();return}data.habits.push({id:crypto.randomUUID(),name,category:$('#habitCategory').value,frequency:$('#habitFrequency').value,durationMinutes,createdAt:new Date().toISOString()});save();e.target.reset();render()});
$('#timerToggle').onclick=toggleTimer;$('#timerFinish').onclick=completeTimer;$('#welcomeForm').addEventListener('submit',e=>{const name=$('#welcomeName').value.trim();if(!name){e.preventDefault();return}data.profile.name=name;data.profile.theme=$('#welcomeTheme').value;data.profile.onboarded=true;save();render()});
document.querySelectorAll('[data-mood]').forEach(button=>button.onclick=()=>{data.plus.moods[today]=Number(button.dataset.mood);save();render()});$('#saveNoteButton').onclick=()=>{data.plus.notes[today]=$('#dailyNote').value.trim();save();render()};
function removeProgramHabits(key){const ids=data.habits.filter(h=>h.programKey===key).map(h=>h.id);data.habits=data.habits.filter(h=>h.programKey!==key);Object.keys(data.completions).forEach(day=>{data.completions[day]=data.completions[day].filter(id=>!ids.includes(id));if(!data.completions[day].length)delete data.completions[day]})}
const connectedAppPairs=[['bevel','appBevel'],['calendar','appCalendar'],['notion','appNotion'],['todoist','appTodoist'],['forest','appForest']];const syncConnectedApps=()=>{data.profile.connectedApps={};connectedAppPairs.forEach(([key,input])=>data.profile.connectedApps[key]=$('#'+input).checked);save();render()};connectedAppPairs.forEach(([,input])=>$('#'+input).addEventListener('change',syncConnectedApps));
$('#profileButton').onclick=()=>{$('#profileName').value=data.profile.name;$('#profileTheme').value=data.profile.theme;$('#programHard75').checked=data.profile.programs.hard75.enabled;$('#programStartDate').value=Object.values(data.profile.programs).find(program=>program.enabled)?.startDate||today;$('#programReset14').checked=data.profile.programs.reset14.enabled;$('#programMove30').checked=data.profile.programs.move30.enabled;$('#programRead30').checked=data.profile.programs.read30.enabled;[['bevel','appBevel'],['calendar','appCalendar'],['notion','appNotion'],['todoist','appTodoist'],['forest','appForest']].forEach(([key,input])=>$('#'+input).checked=!!data.profile.connectedApps[key]);$('#profileDialog').showModal()};
$('#profileForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;data.profile.name=$('#profileName').value.trim();data.profile.theme=$('#profileTheme').value;data.profile.connectedApps={};[['bevel','appBevel'],['calendar','appCalendar'],['notion','appNotion'],['todoist','appTodoist'],['forest','appForest']].forEach(([key,input])=>data.profile.connectedApps[key]=$('#'+input).checked);const startDate=$('#programStartDate').value||today;[['hard75','programHard75'],['reset14','programReset14'],['move30','programMove30'],['read30','programRead30']].forEach(([key,input])=>{data.profile.programs[key]={enabled:$('#'+input).checked,startDate}});Object.entries(timedPrograms).forEach(([key,definition])=>{if(data.profile.programs[key].enabled){definition.rules.forEach((name,index)=>{if(!data.habits.some(h=>h.programKey===key&&h.programRule===index))data.habits.push({id:crypto.randomUUID(),name,frequency:'daily',createdAt:new Date().toISOString(),programKey:key,programRule:index})})}else removeProgramHabits(key)});save();render()});
function openTransaction(type){transactionType=type;$('#transactionDialogLabel').textContent=type==='income'?'CASH IN':'CASH OUT';$('#transactionDialogTitle').textContent=type==='income'?'Add money':'Remove money';$('#transactionSubmit').textContent=type==='income'?'Add to balance':'Remove from balance';$('#transactionDialog').showModal()}$('#addIncomeButton').onclick=()=>openTransaction('income');$('#addExpenseButton').onclick=()=>openTransaction('expense');$('#transactionForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const amount=Number($('#transactionAmount').value),note=$('#transactionNote').value.trim();if(!amount||!note){e.preventDefault();return}data.transactions.push({id:crypto.randomUUID(),type:transactionType,amount,note,date:new Date().toISOString()});save();e.target.reset();render()});
$('#clearTransactions').onclick=()=>{if(data.transactions.length&&confirm('Clear all cash transactions? This cannot be undone.')){data.transactions=[];save();render()}};function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`ledger-backup-${today}.json`;a.click();URL.revokeObjectURL(url)}$('#dataButton').onclick=()=>$('#dataDialog').showModal();$('#saveDataButton').onclick=exportData;$('#deleteDataButton').onclick=()=>{if(confirm('Are you sure you want to delete all Ledger data? This cannot be undone.')){data=JSON.parse(JSON.stringify(defaults));save();$('#dataDialog').close();render();$('#welcomeDialog').showModal()}};render();if(!data.profile.onboarded)$('#welcomeDialog').showModal();
